--- #YAML:1.0
name:               Mojolicious-Plugin-Human
version:            0.4
abstract:           Helpers to print values as human readable form.
author:
    - Dmitry E. Oboukhov <unera@debian.org>,
    - Roman V. Nikolaev <rshadow@rambler.ru>
license:            Perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    DateTime::Format::DateParse:  0
    Mojo::Base:           0
    Test::Compile:        0
resources:
    bugtracker:  https://github.com/dr-co/libmojolicious-plugin-human-perl/issues
    homepage:    https://github.com/dr-co/libmojolicious-plugin-human-perl
    repository:  https://github.com/dr-co/libmojolicious-plugin-human-perl
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
